### ISSUE TITLE
在移动端全景图会模糊

### ISSUE THREAD

**Issue by kevinZengXing** [azuoge/Opanorama#1]
我也用three.js写了一个全景图，在pc端正常和krpano的效果差不多，但在移动端，贴图明显的会糊。请问你知道怎么解决吗？
这个是demo的地址：https://dev-admin.mankuhome.com/test/index.html

**Comment by azuoge** [comment]
图片尺寸是多大的？

**Comment by kevinZengXing** [comment]
8192 * 4096

**Comment by kevinZengXing** [comment]
> 图片尺寸是多大的？

8192 * 4096

**Comment by azuoge** [comment]
换成1024的整数倍且长是宽的两倍，移动端建议2048*1024就行
