### ISSUE TITLE
移动端浏览器访问存在跨域错误的问题

### ISSUE THREAD

**Issue by plutosherry** [azuoge/Opanorama#4]
RT:
浏览器是chrome
错误信息如下：
from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by azuoge** [comment]
你传入了全景图片了吗？？

**Comment by leon-lv8** [comment]
最新版本的chrome浏览器因为canvas图片不能跨域了，所以不能用文件的方式打开，只能在本地开一个服务器，把代码放到服务器上才能避免跨域问题

**Comment by plutosherry** [comment]
确定传入图片了，并且是部署在服务器端iis下的，非本机。
现在的问题是在电脑端可以访问，但是手机移动端无法显示。

**Comment by plutosherry** [comment]
我查看了一下错误代码信息提示是跨域错误的类型，苹果手机端使用chrome不能打开 safari也不行。

**Comment by azuoge** [comment]
贴一下代码吧
